version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./public:/app/public
    depends_on:
      - redis
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: infra/docker/bot.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - api
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: infra/docker/admin.Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://1.234.83.118:3000
    ports:
      - "3001:3000"
    environment:
      - API_URL=http://api:3000
      - HOSTNAME=0.0.0.0
    depends_on:
      - api
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=dydeo484@
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  redis_data:
  n8n_data:
